# Generated by Django 5.0 on 2023-12-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='имя автора')),
                ('born', models.DateField(max_length=100, verbose_name='дата рождения')),
                ('city', models.CharField(max_length=100, verbose_name='город автора')),
            ],
        ),
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_text', models.CharField(max_length=200, verbose_name='название темы')),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.CharField(max_length=10000, verbose_name='текст поста')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='files/', verbose_name='фото ')),
                ('post_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blog.authormodel', verbose_name='автор поста')),
                ('topic', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Blog.topicmodel', verbose_name='тема поста')),
            ],
        ),
    ]
