# Generated by Django 5.0 on 2023-12-08 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='topic_text',
            new_name='topic_title',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='post_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000, verbose_name='название поста'),
            preserve_default=False,
        ),
    ]
