# Generated by Django 5.0 on 2023-12-25 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.authormodel', verbose_name='автор подписки')),
                ('user_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='подписанный пользователь')),
            ],
        ),
    ]
