# Generated by Django 5.0 on 2023-12-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_rename_topic_text_topicmodel_topic_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='topicmodel',
            options={'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
